In [1]:
import numpy as np

In [9]:
l= range(100000)

In [10]:
d= np.arange(100000)

In [11]:
%time for i in range(1,10): y= [x*2 for x in l]

Wall time: 320 ms


In [12]:
%time for i in range(1,10): c= d*2

Wall time: 17 ms


###### 1---Test whether none of the elements of a given array is zero? //use of .all

In [15]:
x = np.array([3,4,5,6,7])
print("Original array:")
print(x)
print("Test begins")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test test begins")
print(np.all(x))

Original array:
[3 4 5 6 7]
Test begins
True
Original array:
[0 1 2 3]
Test test begins
False


###### 2----------- test whether any of the elements of a given array is non-zero? use of .any

In [14]:
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test begins")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test behgins")
print(np.any(x))

Original array:
[1 0 0 0]
Test begins
True
Original array:
[0 0 0 0]
Test behgins
False


###### 3-------- test a given array element-wise for finiteness (not infinity or not a Number)? use of isfinite

In [17]:
a = np.array([1, 0, np.nan , np.inf])
print("Original array")
print(a)
print("Test begins:")
print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
Test begins:
[ True  True False False]


4-------test element-wise for NaN of a given array? use of .isnan

In [19]:
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test begins")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test begins
[False False  True False]


###### 5-------test element-wise for complex number, real number of a given array?use of is real or iscomplex

In [24]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]


###### 6--------Comparison element-wise (greater, greater_equal, less and less_equal) of two given arrays? use of greater greater_equal, less and less_equal

In [25]:
x = np.array([8, 13])
y = np.array([7, 13])
print("Original numbers:")
print(x)
print(y)
print("Comparison for greater")
print(np.greater(x, y))
print("Comparison for greater_equal")
print(np.greater_equal(x, y))
print("Comparisonfor less")
print(np.less(x, y))
print("Comparisonfor less_equal")
print(np.less_equal(x, y))

Original numbers:
[ 8 13]
[ 7 13]
Comparison for greater
[ True False]
Comparison for greater_equal
[ True  True]
Comparisonfor less
[False False]
Comparisonfor less_equal
[False  True]


###### 7-------Element-wise comparison (equal, equal within a tolerance) of two given arrays? use of .equal and .allclose

In [32]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60.0000001, 100.000011])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.          79.          85.          90.         150.
 -135.         120.         -10.          60.0000001  100.000011 ]
Comparison - equal:
[ True  True  True  True  True  True  True  True False False]
Comparison - equal within a tolerance:
True


8-------Create an array and determine the size of the memory occupied by the array? use of .size .itemsize

In [34]:
X = np.array([1, 75, 103, 10005])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[    1    75   103 10005]
Size of the memory occupied by the said array:
16 bytes


###### 9-----------create an array of 10 zeros, 10 ones, 10 fives? use of .ones and .zeroes

In [36]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)
array=np.ones(10)*12
print("An array of 10 twelves:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
An array of 10 twelves:
[12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]


###### 10-------Create an array of the integers from 135 to 160?single dimention use of arange

In [37]:
array=np.arange(135,160)
print("Array of the integers from 135 to 160")
print(array)

Array of the integers from 135 to 160
[135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159]


###### 11------Create an array of all the even integers from 30 to 70? use of arange

In [39]:
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


###### 12-------- Create a 4x4 identity matrix. USE OF RESIZE

In [40]:
array_2D=np.identity(4)
print('4x4 matrix:')
print(array_2D)

4x4 matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###### 13---------create a 3X4 array  use of reshape

In [41]:
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


###### 14------------ITERATE EACH ELEMENT OF ARRAY? USE OF NDITER

In [42]:
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 15------------create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last

In [43]:
v = np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[4:-3])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
 43 44 45 46 47 48 49 50 51]


###### 16------------create a vector of length 5 filled with arbitrary integers from 0 to 10. use of randint

In [44]:
x = np.random.randint(0, 11, 5)
print("5 random numbers betwwen values")
print(x)

5 random numbers betwwen values
[ 9  7  3  4 10]


###### 16------------program to find the number of rows and columns of a given matrix.

In [50]:
m= np.arange(1,13).reshape((4, 3))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)

Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Number of rows and columns of the said matrix:
(4, 3)


###### 17------------multiply values of 2 arrays

In [55]:
x= np.random.randint(3, 11, 4)
print("Vector-2")
print(x)
y= np.random.randint(12, 20, 4)
print("Vector-1")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)

Vector-2
[3 3 9 3]
Vector-1
[19 12 19 12]
Multiply the values of two said vectors:
[ 57  36 171  36]


###### 18-----------program to compute sum of all elements, sum of each column and sum of each row of a given array

In [56]:
x = np.array([[0,1,4],[2,3,6],[4,5,8]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1 4]
 [2 3 6]
 [4 5 8]]
Sum of all elements:
33
Sum of each column:
[ 6  9 18]
Sum of each row:
[ 5 11 17]


###### 19---------- inner product of two given vectors.use of .dot

In [57]:
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


###### 20-----------Create a null vector of size 10 and update sixth value to 11.

In [58]:
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


###### 21-----------Program to reverse an array

In [59]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


###### 22--------------Convert an array to a float type.

In [60]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


###### 23-------------Append values to the end of an array.

In [61]:
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


###### 24-------------Create an empty and a full array.

In [62]:
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),1)
print(y)

[[1.  1.  1.  0. ]
 [4.5 0.  3.  0. ]
 [2.  0.  0.  2. ]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


###### 25---------Find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [64]:
x = np.array([1,2,3,6,7,8])
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  6
Length of one array element in bytes:  4
Total bytes consumed by the elements of the array:  24


###### 26--------------Element of a 1-D array is also present in a second array.

In [66]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40, 10]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40, 10]
Compare each element of array1 and array2
[ True  True False  True False]


###### 27------------Unique elements of an array.

In [71]:
x = np.array([10, 10,40,50,30,10,45,19,19, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 40 50 30 10 45 19 19 20 20 30 30]
Unique elements of the above array:
[10 19 20 30 40 45 50]


###### 28--------Program that return sorted and unique values of input arrays.

In [74]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


###### 29----------Program to find the indices of the maximum and minimum values along the given axis of an array.

In [75]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


###### 30----------programme to resize an array..use of .resize

In [2]:
import numpy as np
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)

[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


###### 31--------------Program to shuffle numbers between 0 and 10

In [3]:
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[2 7 6 8 3 4 0 5 9 1]
Same result using permutation():
[4 8 3 1 9 5 7 2 6 0]


###### 32----------Program to find the most frequent value in an array.

In [5]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 4 3 6 3 2 5 7 0 1 9 4 9 0 5 8 3 9 3 6 2 7 5 6 2 5 8 0 6 0 8 2 3 2 4 1 4
 8 6 3]
Most frequent value in the above array:
2


###### 33------------NumPy program to display all the dates for the month of March, 2017.

In [13]:
print("November, 2020")
print(np.arange('2020-11', '2020-12', dtype='datetime64[D]'))

November, 2020
['2020-11-01' '2020-11-02' '2020-11-03' '2020-11-04' '2020-11-05'
 '2020-11-06' '2020-11-07' '2020-11-08' '2020-11-09' '2020-11-10'
 '2020-11-11' '2020-11-12' '2020-11-13' '2020-11-14' '2020-11-15'
 '2020-11-16' '2020-11-17' '2020-11-18' '2020-11-19' '2020-11-20'
 '2020-11-21' '2020-11-22' '2020-11-23' '2020-11-24' '2020-11-25'
 '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29' '2020-11-30']


###### 34-----------NumPy program to get the dates of yesterday, today and tomorrow

In [9]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-12-17
Today:  2020-12-18
Tomorrow:  2020-12-19


###### 35--------NumPy program to count the number of days of specific month

In [11]:
print("Number of days, February, 2016: ")
print(np.datetime64('2016-03-01') - np.datetime64('2016-02-01'))
print("Number of days, February, 2017: ")
print(np.datetime64('2017-03-01') - np.datetime64('2017-02-01'))
print("Number of days, February, 2018: ")
print(np.datetime64('2018-03-01') - np.datetime64('2018-02-01'))

Number of days, February, 2016: 
29 days
Number of days, February, 2017: 
28 days
Number of days, February, 2018: 
28 days


###### 36-------NumPy program to find the first Monday in May 2021

In [12]:
print("First Monday in May 2021:")
print(np.busday_offset('2021-05', 0, roll='forward', weekmask='Mon'))

First Monday in May 2021:
2021-05-03


###### 37-------NumPy program to find the number of weekdays in March 2017.

In [13]:
print("Number of weekdays in March 2021:")
print(np.busday_count('2021-03', '2021-04'))

Number of weekdays in March 2021:
23


###### 38----------* unpacking notation in Python:

In [18]:
lst = ["Apple", "Banana", "Cherries", "Guava", "Jackfruit"]
x, *y, z = lst
print(x)
print(y)
print(z)
print ("2nd example")
lst = [5, 10, 20, 30]
x, *y = lst
print(x)
print(y)

Apple
['Banana', 'Cherries', 'Guava']
Jackfruit
2nd example
5
[10, 20, 30]


###### 39----------------NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [12]:
x = np.array(['USMAN', 'KHawar', 'Sherjeel', 'data science'], dtype=np.str)
print("Input Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Input Array:
['USMAN' 'KHawar' 'Sherjeel' 'data science']

Capitalized:  ['Usman' 'Khawar' 'Sherjeel' 'Data science']
Lowered:  ['usman' 'khawar' 'sherjeel' 'data science']
Uppered:  ['USMAN' 'KHAWAR' 'SHERJEEL' 'DATA SCIENCE']
Swapcased:  ['usman' 'khAWAR' 'sHERJEEL' 'DATA SCIENCE']
Titlecased:  ['Usman' 'Khawar' 'Sherjeel' 'Data Science']


###### 40--------NumPy program to make the length of each element 15 of a given array and the string centered / left-justified / right-justified with paddings of _

In [21]:
x = np.array(['USMAN', 'khawar', 'Sherjeel', 'data science'], dtype=np.str)
print("Original Array:")
print(x)
centered = np.char.center(x, 15, fillchar='_')
left = np.char.ljust(x, 15, fillchar='_')
right = np.char.rjust(x, 15, fillchar='_')
print("\nCentered =", centered)
print("Left =", left)
print("Right =", right)

Original Array:
['USMAN' 'khawar' 'Sherjeel' 'data science']

Centered = ['_____USMAN_____' '_____khawar____' '____Sherjeel___' '__data science_']
Left = ['USMAN__________' 'khawar_________' 'Sherjeel_______' 'data science___']
Right = ['__________USMAN' '_________khawar' '_______Sherjeel' '___data science']


###### 41---------NumPy program to remove the leading whitespaces of all the elements of a given array.

In [22]:
x = np.array([' ali khan ', ' umair  ', ' piaic  ', '  deltaforce'], dtype=np.str)
print("input Array:")
print(x)
lstripped_char = np.char.lstrip(x)
print("\nRemove the leading whitespaces : ", lstripped_char)

input Array:
[' ali khan ' ' umair  ' ' piaic  ' '  deltaforce']

Remove the leading whitespaces :  ['ali khan ' 'umair  ' 'piaic  ' 'deltaforce']


###### 42----------NumPy program to split the element of a given array with spaces.

In [23]:
x = np.array(['Python PHP Java C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)

Original Array:
['Python PHP Java C++']

Split the element of the said array with spaces: 
[list(['Python', 'PHP', 'Java', 'C++'])]


###### 43------NumPy program to insert a space between characters of all the elements of a given array.

In [2]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)

Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


###### 44-------NumPy program to split the element of a given array to multiple lines. 

In [3]:
import numpy as np
x = np.array(['Python\Exercises, Practice, Solution'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.splitlines(x)
print(r)


Original Array:
['Python\\Exercises, Practice, Solution']
[list(['Python\\Exercises, Practice, Solution'])]


###### 45-------- program to make all the elements of a given string to a numeric string of 5 digits with zeros on its left

In [4]:
import numpy as np
x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.zfill(x, 5)
print("\nNumeric string of 5 digits with zeros:")
print(r) 



Original Array:
['2' '11' '234' '1234' '12345']

Numeric string of 5 digits with zeros:
['00002' '00011' '00234' '01234' '12345']


###### 46---------NumPy program to replace "PHP" with "Python" in the element of a given array.

In [5]:
import numpy as np
x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.replace(x, "PHP", "Python")
print("\nNew array:")
print(r)



Original Array:
['PHP Exercises, Practice, Solution']

New array:
['Python Exercises, Practice, Solution']


###### 47----- NumPy program to test equal, not equal, greater equal, greater and less test of all the elements of two given arrays.

In [6]:
import numpy as np
x1 = np.array(['Hello', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
x2 = np.array(['Hello', 'php', 'Java', 'examples', 'html'], dtype=np.str)
print("\nArray1:")
print(x1)
print("Array2:")
print(x2)
print("\nEqual test:")
r = np.char.equal(x1, x2)
print(r)
print("\nNot equal test:")
r = np.char.not_equal(x1, x2)
print(r)
print("\nLess equal test:")
r = np.char.less_equal(x1, x2)
print(r)
print("\nGreater equal test:")
r = np.char.greater_equal(x1, x2)
print(r)
print("\nLess test:")
r = np.char.less(x1, x2)
print(r)



Array1:
['Hello' 'PHP' 'JS' 'examples' 'html']
Array2:
['Hello' 'php' 'Java' 'examples' 'html']

Equal test:
[ True False False  True  True]

Not equal test:
[False  True  True False False]

Less equal test:
[ True  True  True  True  True]

Greater equal test:
[ True False False  True  True]

Less test:
[False  True  True False False]


###### 48----------- NumPy program to count the number of "P" in a given array, element-wise.

In [8]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("Number of ‘P’:")
r = np.char.count(x1, "P")
print(r)



Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Number of ‘P’:
[1 2 0 0 0]


###### 49---------NumPy program to count the lowest index of "P" in a given array, element-wise.

In [10]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("count the lowest index of ‘P’:")
r = np.char.find(x1, "P")
print(r)



Original Array:
['Python' 'PHP' 'JS' 'EXAMPLES' 'HTML']
count the lowest index of ‘P’:
[ 0  0 -1  4 -1]


###### 50-------NumPy program to check whether each element of a given array is composed of digits only, lower case letters only and upper case letters only.

In [11]:
import numpy as np
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)



Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]
